/* NEMA Drive Navigation - Voice Engine v2
 * Event-driven Turkish voice guidance with cooldowns and priority handling.
 * Browser prototype. Native iOS audio routing will use the same event contract.
 */
(function(){'use strict';
 const state={enabled:true,lastKey:'',lastAt:0,stepKey:'',stepAt:0,limitValue:null,limitAt:0,arrivalAnnounced:false,offRouteAnnounced:false};
 const now=()=>Date.now();
 function speak(text,opts={}){if(!state.enabled||!text)return false;const t=now(),cooldown=opts.cooldownMs??7000,key=opts.key||text;if(!opts.force&&key===state.lastKey&&t-state.lastAt<cooldown)return false;if(typeof speechSynthesis==='undefined')return false;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='tr-TR';u.rate=opts.rate??.98;u.pitch=1;u.volume=opts.volume??1;speechSynthesis.speak(u);state.lastKey=key;state.lastAt=t;return true;}
 function enable(v){state.enabled=!!v;if(!state.enabled&&typeof speechSynthesis!=='undefined')speechSynthesis.cancel();return state.enabled;}
 function maneuver(step,distanceM){if(!step||!Number.isFinite(Number(distanceM)))return false;const m=step.maneuver||{},mod=m.modifier||'';if(m.type==='arrive'){if(state.arrivalAnnounced)return false;state.arrivalAnnounced=true;return speak('Hedefinize ulaştınız.',{key:'arrival',force:true});}const raw=Number(distanceM);const d=raw<100?Math.max(10,Math.round(raw/10)*10):Math.round(raw/50)*50;let action='devam edin';if(m.type==='turn')action=mod==='left'?'sola dönün':mod==='right'?'sağa dönün':mod==='slight left'?'hafif sola dönün':mod==='slight right'?'hafif sağa dönün':'dönün';else if(m.type==='roundabout')action='döner kavşağa girin';else if(m.type==='merge')action='şeride katılın';const road=step.name?` ${step.name} üzerinden`:'';return speak(`${d} metre sonra${road} ${action}.`,{key:'step|'+(m.location||[]).join(',')+'|'+m.type+'|'+mod,cooldownMs:12000});}
 function immediateTurn(step){if(!step)return false;const m=step.maneuver||{};let a=m.modifier==='left'?'Sola':m.modifier==='right'?'Sağa':'';if(m.type==='roundabout')a='Döner kavşağa';else if(m.type==='arrive')return speak('Hedefinize ulaştınız.',{force:true,key:'arrival-now'});else if(!a)a='Devam';return speak(`${a} dönün.`,{force:true,key:'turn-now|'+(m.location||[]).join(',')});}
 function speedLimit(value){const v=Number(value);if(!Number.isFinite(v)||v<5||v>160||v===state.limitValue)return false;state.limitValue=v;state.limitAt=now();return speak(`Yeni hız limiti ${Math.round(v)} kilometre/saat.`,{key:'limit|'+v,cooldownMs:30000});}
 function overLimit(speed,limit){const s=Number(speed),l=Number(limit);if(!Number.isFinite(s)||!Number.isFinite(l)||s<=l+2)return false;return speak('Dikkat. Hız limitini aştınız.',{key:'over-limit',cooldownMs:20000});}
 function enforcement(item){if(!item||item.verified===false)return false;const type=String(item.type||'denetim').toLowerCase();const label=type==='eds'?'doğrulanmış hız denetimi':type==='radar'?'doğrulanmış radar':'doğrulanmış trafik denetimi';const limit=Number(item.limitKmh);const suffix=Number.isFinite(limit)?` Hız limitiniz ${Math.round(limit)} kilometre/saat.`:'';return speak(`İleride ${label} bulunuyor.${suffix}`,{key:'enforcement|'+type+'|'+Math.round(Number(item.distanceM)||0),cooldownMs:60000});}
 function offRoute(stable){if(!stable||state.offRouteAnnounced)return false;state.offRouteAnnounced=true;return speak('Rota dışına çıktınız. Yeni rota hesaplanıyor.',{key:'off-route',force:true});}
 function backOnRoute(){state.offRouteAnnounced=false;}
 function reset(){state.lastKey='';state.stepKey='';state.lastAt=0;state.stepAt=0;state.limitValue=null;state.limitAt=0;state.arrivalAnnounced=false;state.offRouteAnnounced=false;}
 window.NEMAVoice={state,speak,enable,maneuver,immediateTurn,speedLimit,overLimit,enforcement,offRoute,backOnRoute,reset};
})();