/* NEMA Drive Navigation - Traffic Intelligence Core v14
 * Multi-signal lawful Green Wave + vehicle bridge + hardened intelligence loaders.
 * Never recommends exceeding an applicable legal speed limit or invents signal timing.
 */
(function(){'use strict';
 const state={signals:[],enabled:true,legalOnly:true,vehicle:{speedKmh:null,rpm:null,gear:null,batteryV:null,source:null,timestamp:null},bluetoothDevice:null,bluetoothServer:null};
 const clamp=(n,a,b)=>Math.max(a,Math.min(b,n)); const num=(v,d=null)=>Number.isFinite(Number(v))?Number(v):d;
 const kmhToMs=k=>Math.max(0,k)/3.6; const msToKmh=v=>Math.max(0,v)*3.6; const arrivalAt=(d,s)=>{const v=kmhToMs(s);return v>0?d/v:Infinity};
 function normalizeSignal(s){return{id:s.id||('signal-'+Math.random().toString(36).slice(2)),distanceM:Math.max(0,num(s.distanceM,0)),phase:s.phase||'unknown',remainingSec:num(s.remainingSec),greenDurationSec:Math.max(1,num(s.greenDurationSec,30)),cycleSec:Math.max(1,num(s.cycleSec,90)),speedLimitKmh:num(s.speedLimitKmh),confidence:s.confidence||'unknown',source:s.source||'unknown',updatedAt:num(s.updatedAt,Date.now())};}
 function addSignal(s){if(!s||!Number.isFinite(Number(s.distanceM)))return false;state.signals.push(normalizeSignal(s));state.signals.sort((a,b)=>a.distanceM-b.distanceM);return true;}
 function setSignals(list){state.signals=(list||[]).filter(s=>Number.isFinite(Number(s.distanceM))).map(normalizeSignal).sort((a,b)=>a.distanceM-b.distanceM);return state.signals;}
 function clear(){state.signals.length=0;}
 function greenWindow(signal,legalLimitKmh){const s=normalizeSignal(signal);if(s.phase!=='red'||!Number.isFinite(s.remainingSec)||s.confidence==='map'||s.source==='OSM')return null;const requested=num(legalLimitKmh);if(requested==null)return null;const limit=clamp(Math.min(requested,s.speedLimitKmh??requested),5,160),start=Math.max(.5,s.remainingSec),end=start+s.greenDurationSec,minKmh=clamp(msToKmh(s.distanceM/end),5,limit),maxKmh=clamp(msToKmh(s.distanceM/start),5,limit);if(minKmh>maxKmh||arrivalAt(s.distanceM,limit)>end)return null;return{minKmh:Math.round(minKmh),maxKmh:Math.round(maxKmh),greenStartSec:s.remainingSec,greenEndSec:end};}
 function optimize(signals,currentSpeedKmh,defaultLimitKmh){const list=(signals||state.signals).map(normalizeSignal).filter(s=>s.distanceM>=0).sort((a,b)=>a.distanceM-b.distanceM),limit=clamp(num(defaultLimitKmh,50),5,160);if(!list.length)return{status:'unknown-data',speedWindowKmh:null,targetKmh:null,signals:[],message:'Trafik ışığı verisi yok.'};if(list.some(s=>s.phase==='unknown'||s.confidence==='map'||s.source==='OSM'||!Number.isFinite(s.remainingSec)))return{status:'unknown-data',speedWindowKmh:null,targetKmh:null,signals:list.map(s=>({...s,status:'timing-unavailable',window:null})),message:'Canlı sinyal zamanlaması doğrulanmadı. Hız artırma önerisi verilmez.'};let low=5,high=limit;const analyzed=[];for(const s of list){const local=clamp(Math.min(limit,s.speedLimitKmh??limit),5,160);if(s.phase==='green'){high=Math.min(high,local);analyzed.push({...s,status:'green',window:null});continue;}const w=greenWindow(s,local);analyzed.push({...s,status:w?'reachable':'wait',window:w});if(w){low=Math.max(low,w.minKmh);high=Math.min(high,w.maxKmh);}}const valid=low<=high,current=num(currentSpeedKmh,0),target=valid?Math.round(clamp(current>=low&&current<=high?current:(low+high)/2,5,high)):null;return{status:valid?'green-wave':'wait',speedWindowKmh:valid?[Math.round(low),Math.round(high)]:null,targetKmh:target,signals:analyzed,message:valid?`Rota boyunca yasal yeşil dalga: ${Math.round(low)}–${Math.round(high)} km/sa`:'Tüm ışıkları aynı yasal hız aralığında yakalamak mümkün değil; hız artırmayın.'};}
 function next(s,l){return optimize(state.signals,s,l).signals[0]||null;}
 function recommend(distanceM,currentSpeedKmh,legalLimitKmh,signal){const s=normalizeSignal(signal),limit=num(legalLimitKmh);if(limit==null)return{status:'unknown',message:'Yasal hız limiti doğrulanmadı.'};if(s.phase==='green'&&s.confidence!=='map'&&s.source!=='OSM')return{status:'green',message:`Yeşil ışık açık • ${Math.round(distanceM)} m`};const w=s.phase==='red'&&Number.isFinite(s.remainingSec)&&s.confidence!=='map'&&s.source!=='OSM'?greenWindow(s,limit):null;if(w)return{status:'legal-green-window',targetKmh:Math.round(clamp((w.minKmh+w.maxKmh)/2,5,limit)),rangeKmh:[w.minKmh,w.maxKmh],message:`Yeşile yasal hız aralığında ulaşılabilir: ${w.minKmh}–${w.maxKmh} km/sa`};return{status:'unknown',message:'Işık zamanlaması doğrulanmadı; hız artırma önerisi verilmez.'};}
 function ingestVehicle(packet){if(!packet)return null;state.vehicle={speedKmh:num(packet.speedKmh),rpm:num(packet.rpm),gear:packet.gear??null,batteryV:num(packet.batteryV),source:packet.source||'bluetooth',timestamp:Date.now()};if(typeof window!=='undefined')window.dispatchEvent(new CustomEvent('nema:vehicle-data',{detail:state.vehicle}));return state.vehicle;}
 function bluetoothSupported(){return typeof navigator!=='undefined'&&!!navigator.bluetooth;}
 async function connectBluetooth(){if(!bluetoothSupported())throw new Error('Web Bluetooth bu tarayıcıda kullanılamıyor. iOS üretim uygulamasında CoreBluetooth/native bridge gerekir.');const device=await navigator.bluetooth.requestDevice({acceptAllDevices:true}),server=await device.gatt.connect();state.bluetoothDevice=device;state.bluetoothServer=server;device.addEventListener('gattserverdisconnected',()=>{state.bluetoothDevice=null;state.bluetoothServer=null;if(typeof window!=='undefined')window.dispatchEvent(new Event('nema:bluetooth-disconnected'));});return{name:device.name||'Bluetooth cihazı',connected:true};}
 async function disconnectBluetooth(){if(state.bluetoothDevice?.gatt?.connected)state.bluetoothDevice.gatt.disconnect();state.bluetoothDevice=null;state.bluetoothServer=null;if(typeof window!=='undefined')window.dispatchEvent(new Event('nema:bluetooth-disconnected'));return{connected:false};}
 window.NEMATrafficLights={state,addSignal,setSignals,clear,arrivalAt,greenWindow,recommend,next,optimize};window.NEMAGreenWave=window.NEMATrafficLights;window.NEMAVehicle={state,ingestVehicle,bluetoothSupported,connectBluetooth,disconnectBluetooth};
 if(typeof document!=='undefined'){const load=(src,flag)=>{if(window[flag]||document.querySelector(`script[data-${flag}]`))return;const s=document.createElement('script');s.src=src;s.async=true;s.dataset[flag]='1';document.head.appendChild(s);};const boot=()=>{load('nema-drive-data-config.js','nemaDriveDataConfig');load('nema-drive-map-core.js','nemaDriveMapCore');load('nema-drive-offline-cache.js','nemaDriveOffline');load('nema-native-bridge.js','nemaNativeBridge');load('navigation-data-providers.js','nemaDataProviders');load('speed-limit-engine.js','nemaSpeedLimitEngine');load('enforcement-engine.js','nemaEnforcementEngine');load('traffic-engine.js','nemaTrafficEngine');load('navigation-intelligence.js','nemaNavigationIntelligence');load('map-provider.js','nemaMapProvider');load('navigation-voice.js','nemaNavigationVoice');load('navigation-runtime-bridge.js','nemaNavigationRuntime');load('navigation-live-data.js','nemaLiveData');load('navigation-ui-runtime.js','nemaUIRuntime');if('serviceWorker' in navigator){navigator.serviceWorker.register('./sw.js').catch(()=>{});}};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();}
})();
